$(document).ready(function(){
	$('.toggle').click(function(){
		$('.navbar-wrapper').toggleClass('active');
		$(this).hide();
	})
	$('.nav-toggle').click(function(){
		$('.navbar-wrapper').toggleClass('active');
		$('.toggle').show();
	})
})